app:
    resource: '@AppBundle/Controller/Frontend'
    type: annotation
    prefix: /

admin:
    resource: '@AppBundle/Controller/Backend'
    type: annotation
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"